version: "3.8"

services:
  nestjs-app:
    build: .
    container_name: nestjs_app
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: production
      PORT: 9000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: mariadb:11
    container_name: nestjs_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
