version: "3.8"

services:
  backend_test:
    build: ./backends/backend_test
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: development
    networks:
      - service_mynetwork
    volumes:
      - ./backends/backend_test:/app

networks:
  service_mynetwork:
    driver: bridge
